services:
  db_postgres_sort:
    image: postgres
    container_name: db_postgres_sort
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env
    volumes:
      - db_postgres-sort:/var/lib/postgressql/data

  node_app-sort:
    container_name: node_app-sort
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_sort
    env_file:
      - back-end/.env
  react_sort_app:
    container_name: react_sort_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html
  nginx_sort_app:
    container_name: nginx_sort_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db_postgres_sort
      - node_app-sort
      - react_sort_app
volumes:
  db_postgres-sort:
  build_react:
